# Generated by Django 5.0.7 on 2024-07-22 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('engine_model', models.CharField(max_length=100)),
                ('engine_serial_number', models.CharField(max_length=100)),
                ('transmission_model', models.CharField(max_length=100)),
                ('transmission_serial_number', models.CharField(max_length=100)),
                ('drive_axle_model', models.CharField(max_length=100)),
                ('drive_axle_serial_number', models.CharField(max_length=100)),
                ('steer_axle_model', models.CharField(max_length=100)),
                ('steer_axle_serial_number', models.CharField(max_length=100)),
                ('contract_number_date', models.CharField(max_length=100)),
                ('shipment_date', models.DateField()),
                ('end_user', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('additional_options', models.TextField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_machines', to=settings.AUTH_USER_MODEL)),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_machines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField()),
                ('operating_hours', models.IntegerField()),
                ('failure_node', models.CharField(max_length=255)),
                ('failure_description', models.TextField()),
                ('recovery_method', models.CharField(max_length=255)),
                ('spare_parts_used', models.TextField()),
                ('recovery_date', models.DateField()),
                ('downtime', models.IntegerField()),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_claims', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chzsa_app.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('operating_hours', models.IntegerField()),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('organization', models.CharField(max_length=255)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chzsa_app.machine')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_maintenances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
