# Generated by Django 5.0.7 on 2024-07-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chzsa_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
